#theme: jekyll-theme-cayman
remote_theme: "mmistakes/minimal-mistakes@4.19.2"
plugins: jekyll-include-cache
title: Shahrooz Abghari's Licentiate Thesis
description: Blekinge Tekniska Högskola, Department of Computer Science and Engineering
