theme: thelehhman/plainwhite-jekyll
#theme: plainwhite
#jekyll-theme-cayman
#title: Shahrooz Abghari's Licentiate Thesis
#description: Blekinge Tekniska Högskola, Department of Computer Science and Engineering
plainwhite:
  name: Adam Denisov
  tagline: Developer. Designer
  date_format: "%b %-d, %Y"

  social_links:
    twitter: thelehhman
    github:  thelehhman
    linkedIn: in/thelehhman # format: locale/username
