theme: jekyll-theme-cayman
title: PhD Dissertation
description: Blekinge Tekniska Högskola, Department of Computer Science, (October 2020)
author: Shahrooz Abghari
Author's home: "https://www.bth.se/eng/staff/shahrooz-abghari-sab/"
social-network-links:
  email: sab[at]bth.se
